import { NextResponse } from "next/server";

export async function POST(request: Request) {
  const { prompt } = await request.json();

  return NextResponse.json({
    success: true,
    prompt,
    website: {
      navbar: {
        logo: "TheCodeSpark",
        links: ["Home", "About", "Services", "Contact"],
      },
      hero: {
        heading: "AI Generated Website",
        subHeading: `Prompt: ${prompt}`,
        button: "Get Started",
      },
      about: {
        title: "About Us",
        description:
          "This website is currently generated by the demo API. Later we'll replace this with a real AI response.",
      },
      services: [
        "Web Development",
        "AI Solutions",
        "UI/UX Design",
        "Cloud Services",
      ],
      contact: {
        email: "info@thecodespark.in",
        phone: "+91 9876543210",
      },
    },
  });
}